FROM dpage/pgadmin4:latest
# Set environment variables for pgAdmin
# These are for the pgAdmin server itself, NOT the database connection
# ENV PGADMIN_DEFAULT_EMAIL="admin@openimage.com"
# ENV PGADMIN_DEFAULT_PASSWORD="pgadminpassword1234" 
EXPOSE 80