# Generated by Django 5.2.6 on 2025-10-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("you_image_generator", "0001_initial"),
    ]

    operations = []
