# Generated by Django 5.2.6 on 2025-10-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("you_image_generator", "0002_add_metadata_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedimage",
            name="aspect_ratio",
            field=models.CharField(default="1:1", max_length=10),
        ),
        migrations.AddField(
            model_name="generatedimage",
            name="cfg_scale",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generatedimage",
            name="height",
            field=models.IntegerField(default=1024),
        ),
        migrations.AddField(
            model_name="generatedimage",
            name="negative_prompt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generatedimage",
            name="output_format",
            field=models.CharField(default="PNG", max_length=10),
        ),
        migrations.AddField(
            model_name="generatedimage",
            name="provider",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="generatedimage",
            name="seed",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generatedimage",
            name="width",
            field=models.IntegerField(default=1024),
        ),
        migrations.AddIndex(
            model_name="generatedimage",
            index=models.Index(
                fields=["-created_at"], name="you_image_g_created_d5de70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedimage",
            index=models.Index(
                fields=["provider"], name="you_image_g_provide_f558d4_idx"
            ),
        ),
    ]
