# Generated by Django 5.2.7 on 2025-10-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("you_image_generator", "0004_add_tags_and_categories"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="generatedimage",
            name="you_image_g_tags_idx",
        ),
        migrations.RemoveIndex(
            model_name="generatedimage",
            name="you_image_g_category_idx",
        ),
        migrations.RemoveIndex(
            model_name="generatedimage",
            name="you_image_g_favorite_idx",
        ),
        migrations.RemoveIndex(
            model_name="generatedimage",
            name="you_image_g_style_idx",
        ),
        migrations.RemoveField(
            model_name="generatedimage",
            name="category",
        ),
        migrations.RemoveField(
            model_name="generatedimage",
            name="favorite_date",
        ),
        migrations.RemoveField(
            model_name="generatedimage",
            name="is_favorite",
        ),
        migrations.RemoveField(
            model_name="generatedimage",
            name="is_upscaled",
        ),
        migrations.RemoveField(
            model_name="generatedimage",
            name="original_image_id",
        ),
        migrations.RemoveField(
            model_name="generatedimage",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="generatedimage",
            name="style_preset",
        ),
        migrations.RemoveField(
            model_name="generatedimage",
            name="tags",
        ),
    ]
