# Generated by Django 5.2.7 on 2025-10-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "you_image_generator",
            "0005_remove_generatedimage_you_image_g_tags_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedimage",
            name="style_preset",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
