# Generated by Django 5.2.7 on 2025-10-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("you_image_generator", "0006_generatedimage_style_preset"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedimage",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
